export interface SurveyData {
  surveyType: 'adult' | 'child' | '';
  userName: string;
  birthDate: string;
  age: string;
  diagnosis: string;
  modality: string[];
  applicationDate: string;
  professional: string;
  caregiverContact: string;
  updateReasons: string[];
  updateReasonDescription: string;
  livesWith: string;
  spendsMostTimeWith: string;
  organizesRoutine: string;
  accompaniesDisplacements: string;
  routineMorning: string;
  routineMainPeriod: string;
  routineAfternoonNight: string;
  functionalityOptions: string[];
  mainDifficulties: string;
  primaryCaregiver: string;
  otherFamilySupport: string;
  treatmentFacilitators: string;
  treatmentBarriers: string;
  healthNetworkOptions: string[];
  healthNetworkObservations: string;
  occupationalNetworkOptions: string[];
  occupationalNetworkObservations: string;
  logisticalSupportOptions: string[];
  routineSynthesis: string;
  ecomapSynthesis: string;
  familyComposition: string;
  familyArrangementOptions: string[];
  maritalStatusRelevance: string;
  healthDecisionMaker: string;
  familyDivergence: string;
  aiFacilitators: string;
  aiBarriers: string;
  priorityContexts: string[];
  priorityContextsObservations: string;
  pactuationPeople: string[];
  pactuationObservations: string;
  goalsObservations: string;
  professionalSynthesis: string;
  professionalSignature: string;
  date: string;

  // Child Survey Fields
  childLivesWith: string;
  childSpendsMostTimeWith: string;
  childOrganizesRoutine: string;
  childAccompaniesDisplacements: string;
  childRoutineMorning: string;
  childSchoolName: string;
  childSchoolShift: string;
  childSchoolParticipation: string;
  childAfterSchoolTherapies: string;
  childAfterSchoolAccompaniment: string;
  childAfterSchoolResponse: string;
  childAfternoonStaysWith: string;
  childAfternoonActivities: string;
  childNightCaregiver: string;
  childNightRoutine: string;
  childWeekendRoutine: string;
  childCommunitySpaces: string;
  childBehaviorChanges: string;
  childFeedingIndependence: string;
  childFeedingObservations: string;
  childHygieneIndependence: string;
  childHygieneObservations: string;
  childDressingIndependence: string;
  childDressingObservations: string;
  childSleepOptions: string[];
  childSleepObservations: string;
  childInterests: string;
  childRoutineSynthesis: string;

  // Child Survey Fields - Ecomapa
  childPrimaryCaregiver: string;
  childOtherCaregivers: string;
  childCaregiverParticipation: string;
  childCerAccompaniments: string[];
  childCerAccompanimentsOther: string;
  childOtherHealthAccompaniments: string[];
  childOtherHealthAccompanimentsOther: string;
  childUsesMedication: string;
  childMedications: string;
  childSchoolSupport: string;
  childSchoolObservations: string;
  childComplementaryActivities: string;
  childCommunityReligiousSpaces: string;
  childTransportOptions: string[];
  childTransportOther: string;
  childAccessDifficulties: string;
  childTreatmentFacilitators: string;
  childTreatmentBarriers: string;
  childEcomapSynthesis: string;

  // Child Survey Fields - Genograma
  childFather: string;
  childMother: string;
  childLegalGuardian: string;
  childSiblings: string;
  childGrandparentsOther: string;
  childParentsMaritalStatus: string;
  childParentsMaritalStatusOther: string;
  childDecisionMaker: string;
  childTherapeuticAdherence: string;
  childCaregiverDivergence: string;
  childCaregiverDivergenceAspects: string[];
  childCaregiverDivergenceOther: string;
  childFacilitatingCaregiver: string;
  childDisruptiveDynamics: string;
  childConvivesMostWith: string;
  childYieldsToDemands: string;
  childSustainsLimits: string;
  childFamilyConflicts: string;
  childGenogramSynthesis: string;

  // PTS Form Fields
  ptsName: string;
  ptsBirthDate: string;
  ptsAge: string;
  ptsSex: string;
  ptsCity: string;
  ptsPhone: string;
  ptsGuardian: string;
  ptsRelationship: string;
  ptsDiagnosis: string;
  ptsRehabModality: string;
  ptsCreationDate: string;
  ptsReferenceProfessional: string;
  ptsClinicalCondition: string;
  ptsActivityLimitations: string;
  ptsParticipationRestrictions: string;
  ptsEnvironmentalFactors: string;
  ptsFacilitators: string;
  ptsBarriers: string;
  ptsRoutine: string;
  ptsRegularActivities: string;
  ptsDailyAssistants: string;
  ptsSupportPeople: string;
  ptsHealthServices: string;
  ptsSocialNetwork: string;
  ptsTreatmentFacilitators: string;
  ptsTreatmentBarriers: string;
  ptsFamilyComposition: string;
  ptsPrimaryCaregiver: string;
  ptsDecisionAutonomy: string;
  ptsFamilyDynamics: string;
  ptsFamilyObservations: string;
  ptsGoal1: string;
  ptsGoal1Deadline: string;
  ptsGoal1Indicator: string;
  ptsGoal1Priority: string;
  ptsGoal2: string;
  ptsGoal2Deadline: string;
  ptsGoal2Indicator: string;
  ptsGoal2Priority: string;
  ptsGoal3: string;
  ptsGoal3Deadline: string;
  ptsGoal3Indicator: string;
  ptsGoal3Priority: string;
  ptsInterventions: string;
  ptsProfessionalsInvolved: string[];
  ptsProfessionalsInvolvedOther: string;
  ptsCerResponsibilities: string;
  ptsUserResponsibilities: string;
  ptsFamilyResponsibilities: string;
  ptsExternalNetworkResponsibilities: string;
  ptsServicesToActivate: string;
  ptsReferralNeeds: string;
  ptsReevaluationDate: string;
  ptsGoalsEvolution: string;
  ptsReevaluationCriteria: string;
  ptsUnmetGoalsReasons: string;
  ptsFinalObservations: string;
  ptsSignatureProfessional: string;
  ptsSignatureTeam: string;
  ptsSignatureUser: string;
}

export type ArrayField = 'modality' | 'updateReasons' | 'functionalityOptions' | 'healthNetworkOptions' | 'occupationalNetworkOptions' | 'logisticalSupportOptions' | 'familyArrangementOptions' | 'priorityContexts' | 'pactuationPeople' | 'childSleepOptions' | 'childCerAccompaniments' | 'childOtherHealthAccompaniments' | 'childTransportOptions' | 'childCaregiverDivergenceAspects' | 'ptsProfessionalsInvolved';

export interface StepProps {
  data: SurveyData;
  onChange: (field: keyof SurveyData, value: string) => void;
  onArrayChange: (field: ArrayField, value: string) => void;
  onGenerateSynthesis: (field: keyof SurveyData, sectionName: string, contextFields: (keyof SurveyData)[]) => void;
  isGenerating: boolean;
  validationErrors?: Set<string>;
}
